### ISSUE TITLE
IWN throws KeyError

### ISSUE THREAD

**Issue by sidravi1** [adapt-python/adapt#103]
## To replicate

Just using the example in docs:

```
from sklearn.linear_model import RidgeClassifier
from adapt.utils import make_classification_da
from adapt.instance_based import IWN
Xs, ys, Xt, yt = make_classification_da()
model = IWN(RidgeClassifier(0.), Xt=Xt, sigma_init=0.1, random_state=0,
            pretrain=True, pretrain__epochs=100, pretrain__verbose=0)
model.fit(Xs, ys, epochs=100, batch_size=256, verbose=1)
model.score(Xt, yt)
```

## Error

```
2023-06-14 01:58:33.238492: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_14' with dtype double and shape [759,321]
	 [[{{node Placeholder/_14}}]]
2023-06-14 01:58:33.238894: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_14' with dtype double and shape [759,321]
	 [[{{node Placeholder/_14}}]]
Epoch 1/100
2023-06-14 01:58:38.970532: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_14' with dtype double and shape [759,321]
	 [[{{node Placeholder/_14}}]]
2023-06-14 01:58:38.970959: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_2' with dtype double and shape [4135,1]
	 [[{{node Placeholder/_2}}]]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[186], line 3
      1 model_iw = IWN(RandomForestRegressor(500, n_jobs=-1), Xt=Xt, sigma_init=0.1, random_state=0,
      2             pretrain=True, pretrain__epochs=100, pretrain__verbose=0)
----> 3 model_iw.fit(X, y, epochs=100, batch_size=256, verbose=1)
      4 y_pred = model_iw.predict(Xt)

File ~/miniconda3/envs/eg2023/lib/python3.10/site-packages/adapt/instance_based/_iwn.py:212, in IWN.fit(self, X, y, Xt, yt, domains, fit_params_estimator, **fit_params)
    210 def fit(self, X, y=None, Xt=None, yt=None, domains=None,
    211         fit_params_estimator={}, **fit_params):
--> 212     weights = self.fit_weights(X, Xt, **fit_params)
    213     self.fit_estimator(X, y, sample_weight=weights, **fit_params_estimator)
    214     return self

File ~/miniconda3/envs/eg2023/lib/python3.10/site-packages/adapt/instance_based/_iwn.py:237, in IWN.fit_weights(self, Xs, Xt, **fit_params)
    217 def fit_weights(self, Xs, Xt, **fit_params):
    218     """
    219     Fit importance weighting.
    220     
   (...)
    235     weights_ : sample weights
    236     """
--> 237     super().fit(Xs, np.zeros(len(Xs)), Xt, None, None, **fit_params)
    238     return self.predict_weights(Xs)

File ~/miniconda3/envs/eg2023/lib/python3.10/site-packages/adapt/base.py:1155, in BaseAdaptDeep.fit(self, X, y, Xt, yt, domains, **fit_params)
   1151     dataset = dataset.batch(batch_size)
   1153 self.pretrain_ = False
-> 1155 hist = super().fit(dataset, validation_data=validation_data, **fit_params)
   1157 for k, v in hist.history.items():
   1158     self.history_[k] = self.history_.get(k, []) + v

File ~/miniconda3/envs/eg2023/lib/python3.10/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /tmp/__autograph_generated_file_aeowh8j.py:15, in outer_factory.<locals>.inner_factory.<locals>.tf__train_function(iterator)
     13 try:
     14     do_return = True
---> 15     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16 except:
     17     do_return = False

File ~/miniconda3/envs/eg2023/lib/python3.10/site-packages/adapt/instance_based/_iwn.py:203, in IWN.train_step(self, data)
    201 # Update weights
    202 self.optimizer.apply_gradients(zip(gradients, trainable_vars))
--> 203 self.optimizer.apply_gradients(zip(gradients_sigma, [self.sigma_]))
    205 # Return a dict mapping metric names to current value
    206 logs = {"loss": loss, "sigma": self.sigma_}

KeyError: in user code:

    File "/home/sidravi1/miniconda3/envs/eg2023/lib/python3.10/site-packages/keras/engine/training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "/home/sidravi1/miniconda3/envs/eg2023/lib/python3.10/site-packages/keras/engine/training.py", line 1268, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/sidravi1/miniconda3/envs/eg2023/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in run_step  **
        outputs = model.train_step(data)
    File "/home/sidravi1/miniconda3/envs/eg2023/lib/python3.10/site-packages/adapt/instance_based/_iwn.py", line 203, in train_step
        self.optimizer.apply_gradients(zip(gradients_sigma, [self.sigma_]))
    File "/home/sidravi1/miniconda3/envs/eg2023/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1174, in apply_gradients
        return super().apply_gradients(grads_and_vars, name=name)
    File "/home/sidravi1/miniconda3/envs/eg2023/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 650, in apply_gradients
        iteration = self._internal_apply_gradients(grads_and_vars)
    File "/home/sidravi1/miniconda3/envs/eg2023/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1200, in _internal_apply_gradients
        return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/home/sidravi1/miniconda3/envs/eg2023/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1250, in _distributed_apply_gradients_fn
        distribution.extended.update(
    File "/home/sidravi1/miniconda3/envs/eg2023/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 1247, in apply_grad_to_update_var  **
        return self._update_step(grad, var)
    File "/home/sidravi1/miniconda3/envs/eg2023/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 232, in _update_step
        raise KeyError(

    KeyError: 'The optimizer cannot recognize variable Variable:0. This usually means you are trying to call the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.RMSprop.'
```

## Env
```
> uname -r
5.10.82-83.359.amzn2.x86_64
```

Packages:
```
adapt                        0.4.2
tensorflow                   2.12.0
tensorflow-estimator         2.12.0
tensorflow-io-gcs-filesystem 0.32.0
keras                        2.12.0
```

**Comment by antoinedemathelin** [comment]
Hi @sidravi1,

Thank you for reporting this error.

Indeed, we encounter some issues with the 2.12 version of tensorflow. To avoid this error, you can downgrade your tensorflow version to 2.11

Best,
