### ISSUE TITLE
Installation Issues (cp949 codec ?)

### ISSUE THREAD

**Issue by rack570** [adapt-python/adapt#122]
Title: Installation Issues

I'm encountering an error during installation and it's not proceeding. Do you have any insights on this?

(myev) C:\Windows\System32>pip install adapt
Collecting adapt
  Using cached adapt-0.4.4.tar.gz (100 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\정민영\AppData\Local\Temp\pip-install-m1mjiioh\adapt_8d533c069ae44da4a937ba611a3f955a\setup.py", line 5, in <module>
          long_description = (this_directory / "README.md").read_text()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\zzanaconda\envs\myev\Lib\pathlib.py", line 1059, in read_text
          return f.read()
                 ^^^^^^^^
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 12927: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by antoinedemathelin** [comment]
It seems that the bug comes from the setup.py file when reading the README with pathlib.
I tried to fix that. Can you please try:

`pip install git+https://github.com/antoinedemathelin/adapt.git`

and tell me if you still run into a bug ?

**Comment by rack570** [comment]
Oh just executed the command you gave me and it's finally downloaded. Thank you for your quick reply. :) I'll use it well.
